// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XDOCNN_H
#define XDOCNN_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xdocnn_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Crtl_bus_BaseAddress;
} XDocnn_Config;
#endif

typedef struct {
    u32 Crtl_bus_BaseAddress;
    u32 IsReady;
} XDocnn;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XDocnn_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XDocnn_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XDocnn_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XDocnn_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XDocnn_Initialize(XDocnn *InstancePtr, u16 DeviceId);
XDocnn_Config* XDocnn_LookupConfig(u16 DeviceId);
int XDocnn_CfgInitialize(XDocnn *InstancePtr, XDocnn_Config *ConfigPtr);
#else
int XDocnn_Initialize(XDocnn *InstancePtr, const char* InstanceName);
int XDocnn_Release(XDocnn *InstancePtr);
#endif

void XDocnn_Start(XDocnn *InstancePtr);
u32 XDocnn_IsDone(XDocnn *InstancePtr);
u32 XDocnn_IsIdle(XDocnn *InstancePtr);
u32 XDocnn_IsReady(XDocnn *InstancePtr);
void XDocnn_EnableAutoRestart(XDocnn *InstancePtr);
void XDocnn_DisableAutoRestart(XDocnn *InstancePtr);
u32 XDocnn_Get_return(XDocnn *InstancePtr);

void XDocnn_Set_init(XDocnn *InstancePtr, u32 Data);
u32 XDocnn_Get_init(XDocnn *InstancePtr);

void XDocnn_InterruptGlobalEnable(XDocnn *InstancePtr);
void XDocnn_InterruptGlobalDisable(XDocnn *InstancePtr);
void XDocnn_InterruptEnable(XDocnn *InstancePtr, u32 Mask);
void XDocnn_InterruptDisable(XDocnn *InstancePtr, u32 Mask);
void XDocnn_InterruptClear(XDocnn *InstancePtr, u32 Mask);
u32 XDocnn_InterruptGetEnabled(XDocnn *InstancePtr);
u32 XDocnn_InterruptGetStatus(XDocnn *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
