// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdocnn.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDocnn_CfgInitialize(XDocnn *InstancePtr, XDocnn_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDocnn_Start(XDocnn *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDocnn_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_AP_CTRL) & 0x80;
    XDocnn_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XDocnn_IsDone(XDocnn *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDocnn_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XDocnn_IsIdle(XDocnn *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDocnn_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XDocnn_IsReady(XDocnn *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDocnn_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XDocnn_EnableAutoRestart(XDocnn *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDocnn_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_AP_CTRL, 0x80);
}

void XDocnn_DisableAutoRestart(XDocnn *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDocnn_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_AP_CTRL, 0);
}

u32 XDocnn_Get_return(XDocnn *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDocnn_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_AP_RETURN);
    return Data;
}
void XDocnn_Set_init(XDocnn *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDocnn_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_INIT_DATA, Data);
}

u32 XDocnn_Get_init(XDocnn *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDocnn_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_INIT_DATA);
    return Data;
}

void XDocnn_InterruptGlobalEnable(XDocnn *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDocnn_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_GIE, 1);
}

void XDocnn_InterruptGlobalDisable(XDocnn *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDocnn_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_GIE, 0);
}

void XDocnn_InterruptEnable(XDocnn *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDocnn_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_IER);
    XDocnn_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_IER, Register | Mask);
}

void XDocnn_InterruptDisable(XDocnn *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDocnn_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_IER);
    XDocnn_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_IER, Register & (~Mask));
}

void XDocnn_InterruptClear(XDocnn *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDocnn_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_ISR, Mask);
}

u32 XDocnn_InterruptGetEnabled(XDocnn *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDocnn_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_IER);
}

u32 XDocnn_InterruptGetStatus(XDocnn *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDocnn_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XDOCNN_CRTL_BUS_ADDR_ISR);
}

