// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdocnn.h"

extern XDocnn_Config XDocnn_ConfigTable[];

XDocnn_Config *XDocnn_LookupConfig(u16 DeviceId) {
	XDocnn_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDOCNN_NUM_INSTANCES; Index++) {
		if (XDocnn_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDocnn_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDocnn_Initialize(XDocnn *InstancePtr, u16 DeviceId) {
	XDocnn_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDocnn_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDocnn_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

